; Script generated by the HM NIS Edit Script Wizard.
!define PRODUCT_NAME "Will try 3 Files"
!define PRODUCT_VERSION "v1.0.0"
!define PRODUCT_DIR "C:\TestApp"

OutFile "Willtry3Files_Installer-100.exe"
InstallDir "C:\TestApp"
Caption "Will try 3 Files v1.0.0"
ShowInstDetails show
RequestExecutionLevel admin

Page directory ; This adds the page where the user can select the install directory
Page instfiles ; This page actually performs the installation process
 
; Include NSIS plugins and libraries
!addplugindir "/usr/share/nsis/Plugins"
!include LogicLib.nsh
!include WinCore.nsh
!include "/usr/share/nsis/Include/nsisunz.nsh" ; Include the unzip plugin
  
; Function to clean up temporary files (defined before use)
Function CleanupTempFiles
  ; Clean up any remaining ZIP files
    Delete "$INSTDIR\web_push_no_firebase.zip"
  DetailPrint "Cleaned up web_push_no_firebase.zip"
FunctionEnd

; Define constants
!ifndef NSIS_CHAR_SIZE
  !define NSIS_CHAR_SIZE 1
!endif
!ifndef HKEY_LOCAL_MACHINE
  !error HKEY_LOCAL_MACHINE
!endif

Function RegAppendString
System::Store S
Pop $R0 ; append
Pop $R1 ; separator
Pop $R2 ; reg value
Pop $R3 ; reg path
Pop $R4 ; reg hkey
System::Call 'ADVAPI32::RegCreateKey(i$R4,tR3,*i.r1)i.r0'
${If} $0 = 0
    System::Call 'ADVAPI32::RegQueryValueEx(ir1,tR2,i0,*i.r2,i0,*i0r3)i.r0'
    ${If} $0 <> 0
        StrCpy $2 ${REG_SZ}
        StrCpy $3 0
    ${EndIf}
    StrLen $4 $R0
    StrLen $5 $R1
    IntOp $4 $4 + $5
    IntOp $4 $4 + 1 ; For \0
    !if ${NSIS_CHAR_SIZE} > 1
        IntOp $4 $4 * ${NSIS_CHAR_SIZE}
    !endif
    IntOp $4 $4 + $3
    System::Alloc $4
    System::Call 'ADVAPI32::RegQueryValueEx(ir1,tR2,i0,i0,isr9,*ir4r4)i.r0'
    ${If} $0 = 0
    ${OrIf} $0 = ${ERROR_FILE_NOT_FOUND}
        System::Call 'KERNEL32::lstrlen(t)(ir9)t.r0'
        ${If} $0 <> 0
            System::Call 'KERNEL32::lstrcat(t)(ir9,tR1)'
        ${EndIf}
        System::Call 'KERNEL32::lstrcat(t)(ir9,tR0)'
        System::Call 'KERNEL32::lstrlen(t)(ir9)t.r0'
        IntOp $0 $0 + 1
        !if ${NSIS_CHAR_SIZE} > 1
            IntOp $0 $0 * ${NSIS_CHAR_SIZE}
        !endif
        System::Call 'ADVAPI32::RegSetValueEx(ir1,tR2,i0,ir2,ir9,ir0)i.r0'
    ${EndIf}
    System::Free $9
    System::Call 'ADVAPI32::RegCloseKey(ir1)'
${EndIf}
Push $0
System::Store L
FunctionEnd

Section "Section 1" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File "Artikel.pdf"
  File "Final Report.pdf"
  SetOutPath "$INSTDIR"
  SetOverwrite on
  File "web_push_no_firebase.zip"
  SetOutPath "$INSTDIR\web_push_no_firebase"
  SetOverwrite on
  nsisunz::UnzipToLog "$INSTDIR\web_push_no_firebase.zip" "$INSTDIR\web_push_no_firebase"
  Pop $0
  ${If} $0 != "OK"
    DetailPrint "Failed to unzip web_push_no_firebase.zip: $0"
    ; ZIP file kept for debugging since unzip failed
  ${Else}
    DetailPrint "Successfully unzipped web_push_no_firebase.zip to $INSTDIR\web_push_no_firebase"
    ; Clean up the ZIP file after successful extraction
    DetailPrint "Attempting to delete web_push_no_firebase.zip from $INSTDIR"
    Delete "$INSTDIR\web_push_no_firebase.zip"
    DetailPrint "Successfully cleaned up web_push_no_firebase.zip"
  ${EndIf}
  Call CleanupTempFiles
SectionEnd

Function .onGUIEnd
    ExecShell "open" "$INSTDIR"
FunctionEnd